[build]
publish = "public"
command = "hugo"
#command = "tinacms build && hugo --gc --minify --baseURL https://docs.neuralvibes.com/"

[context.production.environment]
HUGO_VERSION = "0.120.2"
GO_VERSION = "1.21.0"
NODE_VERSION = "20.5.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.120.2"
GO_VERSION = "1.21.0"
NODE_VERSION = "20.5.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.120.2"
GO_VERSION = "1.21.0"
NODE_VERSION = "20.5.1"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.120.2"
GO_VERSION = "1.21.0"
NODE_VERSION = "20.5.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
